- name: add repository 'ppa:ubuntu-mate-dev/ppa'
  apt_repository:
    repo: 'ppa:ubuntu-mate-dev/ppa'
  ignore_errors: yes
  tags: [mini-desktop]
  
- name: add repository 'ppa:ubuntu-mate-dev/trusty-mate'
  apt_repository:
    repo: 'ppa:ubuntu-mate-dev/trusty-mate'
  ignore_errors: yes
  tags: [mini-desktop]
  
- name:  gnome-classic-session is present
  apt: name="{{ item }}" state=installed 
  with_items:
     - vnc4server
     - xbase-clients
     - nautilus-open-terminal
     - control-center
     - liberation-mono-fonts
     - xrdp
     - tigervnc-server
  ignore_errors: yes
  tags: [mini-desktop]
  
- name: 設定 selinux 給予權限
  shell: chcon --type=bin_t /usr/sbin/xrdp
  ignore_errors: yes
  tags:  [mini-desktop]

- name: 設定 selinux 給予權限
  shell: chcon --type=bin_t /usr/sbin/xrdp-sesman
  ignore_errors: yes
  tags:  [mini-desktop]


- name: Ububtu xrdp service is restarted
  service:
    name: xrdp
    state: restarted
  tags: [mini-desktop]
  
  
