- name: add repository 'ppa:ubuntu-mate-dev/ppa'
  apt_repository:
    repo: 'ppa:ubuntu-mate-dev/ppa'
  ignore_errors: yes
  tags: [mini-desktop]
  
- name: add repository 'ppa:ubuntu-mate-dev/trusty-mate'
  apt_repository:
    repo: 'ppa:ubuntu-mate-dev/trusty-mate'
  ignore_errors: yes
  tags: [mini-desktop]
  
- name: xrdp is present
  apt:
    name: xrdp
    force: yes
  ignore_errors: yes
  tags: [mini-desktop]

- name: ubuntu-mate-core is present
  apt:
    name:lightdm
    force: yes
  ignore_errors: yes
  tags: [mini-desktop]

- name: ubuntu-mate-desktop is present
  apt:
    name: lightdm-gtk-greeter
    force: yes
  ignore_errors: yes
  tags: [mini-desktop]


- name: Ububtu xrdp service is restarted
  service:
    name: xrdp
    state: restarted
  tags: [mini-desktop]
  
  
