---

# Name of the separate running Red Hat JBoss EAP instance
jboss_eap_instance_name: default

# Red Hat JBoss EAP admin user name
jboss_eap_instance_admin_user: redhat

# Red Hat JBoss EAP admin password ("redhat123!") hashed according to HEX( MD5( username ':' realm ':' password))
jboss_eap_instance_admin_password: ba2caa9378fa898f1dea88804abe52b4

# Red Hat JBoss EAP admin user groups
jboss_eap_instance_admin_groups:

# System user configuration
jboss:
  user: jboss
  group: jboss
  group_id: 500
  user_home: "/opt/jboss"

# Value for the xms and xmx (both are set equal)
jvm_xm: 512

# Port offset for the JBoss EAP instance
jboss_eap_instance_port_offset: 0

# Port used only during updates using the CLI (port should be available)
jboss_eap_instance_cli_default_port: 8888

# Name of the used standalone XML file
jboss_eap_instance_standalone_file: standalone.xml


######### CLI files used for the JBoss EAP configuration

# List of CLI files.
cli_list: { }

# Local directory containing the CLI files in cli_list. Mandatory if 'cli_list' is not empty.
cli_dir: ""


######### Applications retrieved per file copy

# List of the local appplications to be deployed.
app_list: { }

# Local directory containing the files listed in app_list. Mandatory if 'app_list' is not empty.
app_dir: ""


######### Applications retrieved over Nexus

# List of the nexus/maven applications to be deployed.
app_mvn_list: { }

# Nexus connectivity information
nexus_user: ""
nexus_password: ""
nexus_host: ""
nexus_repository_id: ""
